// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElProgress: typeof import('element-plus/es')['ElProgress']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MenuItem: typeof import('./src/components/TreeMenu/MenuItem.vue')['default']
    ReSubMenu: typeof import('./src/components/TreeMenu/ReSubMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMemu: typeof import('./src/components/TreeMenu/SubMemu.vue')['default']
    TreeMenu: typeof import('./src/components/TreeMenu/index.vue')['default']
  }
}
